version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: packs/install.sh
      runas: root
  ApplicationStop:
    - location: packs/stop.sh
      runas: root
  ApplicationStart:
    - location: packs/start.sh
      runas: root
  
